services:
  app:
    image: vacate:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
    secrets:
      - Database__Password
    environment:
      Database__Host: database
      Database__Database: vacate
      Database__Username: postgres
  database:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/Database__Password
      POSTGRES_DB: vacate
    secrets:
      - Database__Password
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -d vacate -c 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

secrets:
  Database__Password:
    file: .password
